<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: DejaVu Sans, sans-serif; padding: 20px; }
        header, footer { text-align: center; background: #29a3a3; color: white; padding: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { padding: 8px; border: 1px solid #ccc; }
        th { background: #f2f2f2; }
        .total-row td { font-weight: bold; font-size: 16px; }
    </style>
</head>
<body>
    <header><h2>USP Student Finance Summary</h2></header>

    <p><strong>Student ID:</strong> {{ $student->student_id }}</p>
    <p><strong>Name:</strong> {{ $student->first_name }} {{ $student->last_name }}</p>

    <table>
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($courses as $course)
                <tr>
                    <td>{{ $course->course_code }}</td>
                    <td>${{ $course->course_price }}</td>
                </tr>
            @endforeach
            <tr>
                <td>Subtotal</td>
                <td>${{ $subtotal }}</td>
            </tr>
            <tr>
                <td>Service Fee</td>
                <td>${{ $service_fee }}</td>
            </tr>
            <tr class="total-row">
                <td>Total</td>
                <td>${{ $total }}</td>
            </tr>
        </tbody>
    </table>

    <footer><p>Generated by USP Website</p></footer>
</body>
</html>
