<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            padding: 20px;
        }
        header, footer {
            background-color: #29a3a3;
            color: white;
            text-align: center;
            padding: 10px;
        }
        h2 {
            margin-top: 20px;
            text-align: center;
        }
        .student-info {
            margin: 20px 0;
            padding: 10px;
            background: #f1f1f1;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        th, td {
            padding: 8px;
            border: 1px solid #999;
            font-size: 14px;
        }
        th {
            background-color: #eee;
        }
    </style>
</head>
<body>
    <header>
        <h1>USP Completed Courses Report</h1>
    </header>

    <div class="student-info">
        <p><strong>Name:</strong> {{ $student->first_name }} {{ $student->last_name }}</p>
        <p><strong>Student ID:</strong> {{ $student->student_id }}</p>
        <p><strong>Program:</strong> {{ $student->program_name ?? 'N/A' }}</p>
    </div>

    <h2>Completed Courses</h2>
    <table>
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Course Name</th>
                <th>Grade</th>
                <th>Semester</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($courses as $course)
                <tr>
                    <td>{{ $course['course_code'] }}</td>
                    <td>{{ $course['course_name'] }}</td>
                    <td>{{ $course['grade'] }}</td>
                    <td>{{ $course['semester'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <footer>
        <p>Generated by USP Website</p>
    </footer>
</body>
</html>
